// Generated by CoffeeScript 1.4.0
(function() {
  var express, http, http_server, io, messages, path, routes, serv_io, server;

  express = require('express');

  routes = require('./routes');

  http = require('http');

  path = require('path');

  server = express();

  io = require('socket.io');

  http_server = http.createServer(server);

  serv_io = io.listen(http_server);

  serv_io.configure(function() {
    serv_io.enable('browser client etag');
    serv_io.set('log level', 1);
    return serv_io.set('transports', ['websocket', 'flashsocket', 'htmlfile', 'xhr-polling', 'jsonp-polling']);
  });

  server.configure(function() {
    server.set('port', process.env.PORT || 3000);
    server.set('views', __dirname + '/views');
    server.set('view engine', 'jade');
    server.use(express.favicon());
    server.use(express.logger('dev'));
    server.use(express.bodyParser());
    server.use(express.methodOverride());
    server.use(express.cookieParser('seeecrets string'));
    server.use(express.session());
    server.use(server.router);
    return server.use(express["static"](path.join(__dirname, 'public')));
  });

  server.configure('development', function() {
    return server.use(express.errorHandler());
  });

  server.get('/', routes.index);

  messages = new Array();

  Array.prototype.inject = function(data) {
    return this.push(data);
  };

  serv_io.sockets.on('connection', function(client) {
    console.log("New Connection ", client.id);
    client.on('init', function() {
      return serv_io.sockets.emit('news', messages);
    });
    client.on('new_post', function(data) {
      messages.inject(data);
      serv_io.sockets.emit('news', messages);
      return serv_io.sockets.emit('new_post', data);
    });
    return client.on('disconnect', function() {
      return console.log("Disconnected: ", client.id);
    });
  });

  http_server.listen(server.get('port'), function() {
    return console.log('express server on port ' + server.get('port'));
  });

}).call(this);
